In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [51]:
dataset = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv')
x = dataset.iloc[:, 1:3].values
y = dataset.iloc[:, 0].values

In [52]:
print(x)

[['male' 22.0]
 ['female' 38.0]
 ['female' 26.0]
 ...
 ['female' 19.0]
 ['female' 28.0]
 ['male' 32.0]]


In [53]:
print(y)

[0 1 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0
 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 0 1 0 0
 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
 0 1 1 1 0 1 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 0 1 0 1 1
 0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 1
 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 1 1
 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1
 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0 0 1
 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0
 1 1 1 0 0 0 0 0 1 1 1 1 

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 22.0]
 [1.0 0.0 38.0]
 [1.0 0.0 26.0]
 ...
 [1.0 0.0 19.0]
 [1.0 0.0 28.0]
 [0.0 1.0 32.0]]


In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=1/3, random_state=0)

In [56]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [57]:
y_pred = regressor.predict(x_test)

In [60]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.78 1.  ]
 [0.19 0.  ]
 [0.79 1.  ]
 [0.78 1.  ]
 [0.19 0.  ]
 [0.79 1.  ]
 [0.19 0.  ]
 [0.19 0.  ]
 [0.78 1.  ]
 [0.19 0.  ]
 [0.78 1.  ]
 [0.21 0.  ]
 [0.17 1.  ]
 [0.77 0.  ]
 [0.78 1.  ]
 [0.19 0.  ]
 [0.78 0.  ]
 [0.79 1.  ]
 [0.19 1.  ]
 [0.18 0.  ]
 [0.19 0.  ]
 [0.18 1.  ]
 [0.19 0.  ]
 [0.19 0.  ]
 [0.19 0.  ]
 [0.19 0.  ]
 [0.78 1.  ]
 [0.8  1.  ]
 [0.19 0.  ]
 [0.19 0.  ]
 [0.17 0.  ]
 [0.19 0.  ]
 [0.77 1.  ]
 [0.78 1.  ]
 [0.78 1.  ]
 [0.19 0.  ]
 [0.79 1.  ]
 [0.19 1.  ]
 [0.77 1.  ]
 [0.18 0.  ]
 [0.19 0.  ]
 [0.78 0.  ]
 [0.78 1.  ]
 [0.79 1.  ]
 [0.2  0.  ]
 [0.78 1.  ]
 [0.78 1.  ]
 [0.78 0.  ]
 [0.19 0.  ]
 [0.18 1.  ]
 [0.77 1.  ]
 [0.77 1.  ]
 [0.2  1.  ]
 [0.78 0.  ]
 [0.18 0.  ]
 [0.79 1.  ]
 [0.19 0.  ]
 [0.17 1.  ]
 [0.8  1.  ]
 [0.78 1.  ]
 [0.78 1.  ]
 [0.18 0.  ]
 [0.19 0.  ]
 [0.17 1.  ]
 [0.18 0.  ]
 [0.2  1.  ]
 [0.79 1.  ]
 [0.19 0.  ]
 [0.8  1.  ]
 [0.18 0.  ]
 [0.8  0.  ]
 [0.78 1.  ]
 [0.17 1.  ]
 [0.8  0.  ]
 [0.2  0.  ]
 [0.18 0.  ]
 [0.16 0.  ]